include Makefile.deps

BUILD = build
SRC   = src
OBJ   = obj
PROJECT_NAME ?= blink

CC = $(CROSS_PREFIX)gcc
LD = $(CROSS_PREFIX)ld
STRIP   = $(CROSS_PREFIX)strip
OBJCOPY = $(CROSS_PREFIX)objcopy
OBJDUMP = $(CROSS_PREFIX)objdump

BOOT_MODE ?= eeprom
MARCH = rv32i_zicsr
MABI  = ilp32

LDSCRIPT = $(SHARED_DIR)/ldscripts/$(BOOT_MODE).ld
RUNTIME  = $(SHARED_DIR)/runtime/crt0.S

INCLUDE += -I $(SHARED_DIR)/include \
           -I $(SHARED_DIR)/periphery \
           -I $(SHARED_DIR)/runtime \
           -I $(SHARED_DIR)/libs \
           -I $(HAL_DIR)/core/Include \
           -I $(HAL_DIR)/peripherals/Include \
           -I $(HAL_DIR)/utilities/Include

LIBS    += -lc
CFLAGS  += -Os -MD -fstrict-volatile-bitfields -fno-strict-aliasing \
           -march=$(MARCH) -mabi=$(MABI) -fno-common -fno-builtin-printf
LDFLAGS += -nostdlib -lgcc -mcmodel=medlow -nostartfiles -ffreestanding \
           -Wl,-Bstatic,-Map,$(OBJ)/$(PROJECT_NAME).map,--print-memory-usage \
           -march=$(MARCH) -mabi=$(MABI) -specs=nano.specs -lnosys \
           -L$(SHARED_DIR)/ldscripts -T$(LDSCRIPT)

CORE_SOURCES := $(HAL_DIR)/peripherals/Source/mik32_hal.c \
                $(HAL_DIR)/peripherals/Source/mik32_hal_pcc.c \
                $(HAL_DIR)/peripherals/Source/mik32_hal_gpio.c \
                $(SHARED_DIR)/libs/uart_lib.c \
                $(RUNTIME)

SOURCES := $(CORE_SOURCES) $(wildcard $(SRC)/*.c $(SRC)/*.S)

OBJECTS := $(filter %.o,$(SOURCES:%.c=%.o) $(SOURCES:%.S=%.o))
OBJECTS := $(addprefix $(OBJ)/,$(OBJECTS))

HEX = $(BUILD)/$(PROJECT_NAME).hex
ELF = $(BUILD)/$(PROJECT_NAME).elf
